In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
# split the dataset for training and testing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

music_data = pd.read_csv('music.csv')
music_data

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [27]:
# preparing and cleaning the data 
# split the dataset: input dataset and output dataset 
X = music_data.drop(columns=['genre'])  # create a new dataset without genre column
# X  # the input dataset
y = music_data['genre']
# y # the output dataset: the prediction or the answers
# allocate 20% of data for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [28]:
# create an instance of decision tree class
model = DecisionTreeClassifier()
# train the model
model.fit(X_train, y_train)
# ask the model to make prediction
predictions = model.predict(X_test)  # this method will pass 2D array
# predictions

In [29]:
# calculating the accuracy: compare the prediction with the actually value we have
# expected values: y_test; actual values: predictions
score = accuracy_score(y_test, predictions) # range of 0 to 1
score

1.0